[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "eval_eval"
description = "Helpers for evaluating LLM Eval frameworks."
requires-python = ">=3.12"
dynamic = ["version"]

[tool.setuptools]
packages = ["eval_eval"]